Created a tdd.py file for the functions and test folder which has a test file named, test_tdd.py 

 test file error fixed


